resources:
  - url: http://127.0.0.1:5000/keba-charger-card.js
    type: module
views:
  - cards:
      - type: custom:keba-charger-card
        name: Keba Card Development
        entity: sun.sun
        test_gui: true
